XIS: EQU 0x1010  
SECTION
TRIANGULO: EQU 0xg10
BOLA:


EQU 4
EQU 300
SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
L1: DIV DOIS
STORE  NEW_DATA
SECTION TEXT
MULT DOIS
TRIANGULO
QUADRADO: EQU -3
EQU 2
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA ;pedro
OUTPUT TMP_DATA
COPY NEW_DATA,OLD_DATA
LOAD OLD_DATA ;testinho teste
JMPP L1
XIS
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
SECTION TEXT
SECTION DATA
9joy: const 3
g4y: space
umtestebacanabembananaparatestarseissofuncionacarau: SPACE
OLAZINHO: EQU 47
cag@$o: space
OLAZINHO
mey_av: space
m4ria: BOLA
_mey_av: space
OLAZINHO: EQU 32
__meyav: blobsky: space
meyav_: space
cag%$o: const 3
OLAZINHO
g00ai: const 2
substitoar: BOLA